apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    app: myapp

  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31600

  type: NodePort  
